name: bpkh_xi_yogyakarta
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.1.0
  google_fonts: 3.0.1
  flutter_spinkit: 5.1.0
  http: 0.13.4
  pull_to_refresh: 2.0.0
  shimmer: 2.0.0
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  fluttertoast: 8.0.9
  url_launcher: 6.1.2
  cool_alert: any
  shared_preferences: 2.0.15
  webview_flutter: any
  cloud_firestore: 3.1.14
  firebase_core: 1.20.0
  firebase_messaging: 11.4.0
  flutter_local_notifications: 9.7.0
  firebase_auth: 3.6.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

